server {
    listen 127.0.0.1:__FALLBACK_PORT__ ssl http2;
    server_name __SITE_DOMAIN__;

    ssl_certificate /etc/letsencrypt/live/__SITE_DOMAIN__/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/__SITE_DOMAIN__/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}